server:
  port: 8181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  config:
    import:
      - classpath:/secret.yml
  servlet:
    multipart:
      enabled: true
      location: C:/test/final_project_file_upload
      max-request-size: 30MB # 한번에 최대 업로드 가능한 용량
      max-file-size: 10MB # 파일 하나의 최대 크기
  jackson:
    serialization:
      fail-on-empty-beans: false

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

#cloud:
#  aws:
#    credentials:
#      access-key: 엑세스 키
#      secret-key: 시크릿 키
#    s3:
#      bucket: 버킷 이름
#    region:
#      static: 지역
#    stack:
#      auto: false


